services:
  db:
    image: postgres:18-alpine
    container_name: postgres_dev
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build: .
    container_name: contacts_app
    ports:
      - "8080:8080"
    environment:
      # Passamos as credenciais do banco para o Spring
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_SECURITY_JWT_SECRET: ${JPA_SECRET}
    depends_on:
      - db

volumes:
  postgres_data:
